In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('student_info.csv')
df

,student_id,name,gender,age,grade_level,math_score,reading_score,writing_score,attendance_rate,parent_education,study_hours,internet_access,lunch_type,extra_activities,final_result
0,S1,Student_1,Other,17,10,74,61,90,94.660002,Master's,4.120192,Yes,Free or reduced,Yes,Fail
1,S2,Student_2,Male,17,12,99,70,91,93.173227,Bachelor's,2.886505,No,Free or reduced,No,Pass
2,S3,Student_3,Other,17,9,59,60,99,98.631098,PhD,1.909926,No,Free or reduced,No,Fail
3,S4,Student_4,Other,17,12,70,88,69,96.419620,PhD,1.664740,No,Standard,No,Pass
4,S5,Student_5,Male,15,9,85,77,94,91.332105,PhD,2.330918,Yes,Free or reduced,No,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S996,Student_996,Female,15,10,76,75,55,94.127440,Bachelor's,2.212263,Yes,Free or reduced,No,Fail
996,S997,Student_997,Female,17,12,83,68,98,86.911592,Bachelor's,3.552898,No,Free or reduced,Yes,Fail
997,S998,Student_998,Other,16,10,60,77,92,80.139645,PhD,2.400027,No,Free or reduced,No,Pass
998,S999,Student_999,Other,17,9,94,66,97,88.069619,PhD,4.713490,No,Free or reduced,Yes,Pass
999,S1000,Student_1000,Male,17,9,96,92,93,84.695088,PhD,1.262504,No,Free or reduced,Yes,Pass

In [3]:
df.head()

,student_id,name,gender,age,grade_level,math_score,reading_score,writing_score,attendance_rate,parent_education,study_hours,internet_access,lunch_type,extra_activities,final_result
0,S1,Student_1,Other,17,10,74,61,90,94.660002,Master's,4.120192,Yes,Free or reduced,Yes,Fail
1,S2,Student_2,Male,17,12,99,70,91,93.173227,Bachelor's,2.886505,No,Free or reduced,No,Pass
2,S3,Student_3,Other,17,9,59,60,99,98.631098,PhD,1.909926,No,Free or reduced,No,Fail
3,S4,Student_4,Other,17,12,70,88,69,96.419620,PhD,1.664740,No,Standard,No,Pass
4,S5,Student_5,Male,15,9,85,77,94,91.332105,PhD,2.330918,Yes,Free or reduced,No,Pass

In [4]:
df.tail()

,student_id,name,gender,age,grade_level,math_score,reading_score,writing_score,attendance_rate,parent_education,study_hours,internet_access,lunch_type,extra_activities,final_result
995,S996,Student_996,Female,15,10,76,75,55,94.127440,Bachelor's,2.212263,Yes,Free or reduced,No,Fail
996,S997,Student_997,Female,17,12,83,68,98,86.911592,Bachelor's,3.552898,No,Free or reduced,Yes,Fail
997,S998,Student_998,Other,16,10,60,77,92,80.139645,PhD,2.400027,No,Free or reduced,No,Pass
998,S999,Student_999,Other,17,9,94,66,97,88.069619,PhD,4.713490,No,Free or reduced,Yes,Pass
999,S1000,Student_1000,Male,17,9,96,92,93,84.695088,PhD,1.262504,No,Free or reduced,Yes,Pass

In [5]:
df.describe()

,age,grade_level,math_score,reading_score,writing_score,attendance_rate,study_hours
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,15.999000,10.473000,75.165000,74.293000,75.150000,89.879179,2.978380
std,0.817109,1.136029,14.304349,14.312652,14.395094,5.725007,1.167780
min,15.000000,9.000000,50.000000,50.000000,50.000000,80.000614,1.015673
25%,15.000000,9.000000,63.000000,62.000000,63.000000,84.971772,1.955287
50%,16.000000,10.000000,75.000000,74.000000,75.000000,89.980889,2.962665
75%,17.000000,12.000000,88.000000,86.000000,88.000000,94.629778,3.994360
max,17.000000,12.000000,99.000000,99.000000,99.000000,99.954988,4.997843

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        1000 non-null   object
 1   name              1000 non-null   object
 2   gender            1000 non-null   object
 3   age               1000 non-null   int64
 4   grade_level       1000 non-null   int64
 5   math_score        1000 non-null   int64
 6   reading_score     1000 non-null   int64
 7   writing_score     1000 non-null   int64
 8   attendance_rate   1000 non-null   float64
 9   parent_education  1000 non-null   object
 10  study_hours       1000 non-null   float64
 11  internet_access   1000 non-null   object
 12  lunch_type        1000 non-null   object
 13  extra_activities  1000 non-null   object
 14  final_result      1000 non-null   object
dtypes: float64(2), int64(5), object(8)
memory usage: 117.3+ KB

In [7]:
df.dtypes

student_id           object
name                 object
gender               object
age                   int64
grade_level           int64
math_score            int64
reading_score         int64
writing_score         int64
attendance_rate     float64
parent_education     object
study_hours         float64
internet_access      object
lunch_type           object
extra_activities     object
final_result         object
dtype: object

In [8]:
df.isnull().sum()

student_id          0
name                0
gender              0
age                 0
grade_level         0
math_score          0
reading_score       0
writing_score       0
attendance_rate     0
parent_education    0
study_hours         0
internet_access     0
lunch_type          0
extra_activities    0
final_result        0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [17]:
for col in df.select_dtypes(include='object').columns:
    df[col]=df[col].fillna(df[col].mode()[0])

In [20]:
num_cols=df.select_dtypes(include=np.number).columns

for col in num_cols:
    Q1=df[col].quantile(0.25)
    Q3=df[col].quantile(0.75)

    IQR=Q3-Q1

    lower=Q1-1.5*IQR
    upper=Q3+1.5*IQR

    df=df[(df[col]>=lower) & (df[col]<=upper)]

print("\nSHAPE AFTER OUTLIER REMOVAL:", df.shape)

SHAPE AFTER OUTLIER REMOVAL: (1000, 15)

In [22]:
df['math score log'] = np.log1p(df['math_score'])

print("\nTRANSFORMED DATA:\n", df[['math_score', 'math score log']].head())

TRANSFORMED DATA:
    math_score  math score log
0          74        4.317488
1          99        4.605170
2          59        4.094345
3          70        4.262680
4          85        4.454347