In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('salary_data.csv')
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
df.tail()

    YearsExperience    Salary
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [5]:
df.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes

In [7]:
df.dtypes

YearsExperience    float64
Salary             float64
dtype: object

In [8]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df['Salaryroup']=pd.cut(df['Salary'],bins=[25000,50000,75000,100000,125000],labels=['25000-50000','50000-75000','75000-100000','100000-125000'])

In [16]:
grouped=df.groupby('Salaryroup',observed=True)['YearsExperience']

In [17]:
summary=grouped.agg(['mean','median','min','max','std'])

In [18]:
summary

                 mean  median  min   max       std
Salaryroup
25000-50000    1.6200    1.50  1.1   2.2  0.465833
50000-75000    3.8750    3.95  2.9   5.1  0.718743
75000-100000   6.2200    6.00  5.3   7.1  0.725948
100000-125000  9.2125    9.25  7.9  10.5  0.935701

In [11]:
print(df.groupby('Salaryroup',observed=True)['YearsExperience'].mean())

Salaryroup
25000-50000      1.6200
50000-75000      3.8750
75000-100000     6.2200
100000-125000    9.2125
Name: YearsExperience, dtype: float64

In [19]:
grouped.apply(list)

Salaryroup
25000-50000                              [1.1, 1.3, 1.5, 2.0, 2.2]
50000-75000      [2.9, 3.0, 3.2, 3.2, 3.7, 3.9, 4.0, 4.0, 4.1, ...
75000-100000                             [5.3, 5.9, 6.0, 6.8, 7.1]
100000-125000           [7.9, 8.2, 8.7, 9.0, 9.5, 9.6, 10.3, 10.5]
Name: YearsExperience, dtype: object

In [12]:
print(df.groupby('Salaryroup',observed=True)['YearsExperience'].median())

Salaryroup
25000-50000      1.50
50000-75000      3.95
75000-100000     6.00
100000-125000    9.25
Name: YearsExperience, dtype: float64

In [13]:
print(df.groupby('Salaryroup',observed=True)['YearsExperience'].apply(lambda x:x.mode()[0]))

Salaryroup
25000-50000      1.1
50000-75000      3.2
75000-100000     5.3
100000-125000    7.9
Name: YearsExperience, dtype: float64

In [14]:
print(df.groupby('Salaryroup',observed=True)['YearsExperience'].max())

Salaryroup
25000-50000       2.2
50000-75000       5.1
75000-100000      7.1
100000-125000    10.5
Name: YearsExperience, dtype: float64

In [15]:
print(df.groupby('Salaryroup',observed=True)['YearsExperience'].min())

Salaryroup
25000-50000      1.1
50000-75000      2.9
75000-100000     5.3
100000-125000    7.9
Name: YearsExperience, dtype: float64

In [20]:
df = pd.read_csv("Iris.csv")

print(df[df['Species'] == 'Iris-setosa'].describe())
print(df[df['Species'] == 'Iris-versicolor'].describe())
print(df[df['Species'] == 'Iris-virginica'].describe())

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000